### PR TITLE
Update to version 3.2.4 requires RSGISLib >= 4.0.0

### PR DESCRIPTION
**Pull request by petebunting**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
I think we need to rebuild `py6s`, `pysolar` etc as they look seriously out of date. I'll send in some PRs.

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@ocefpaf any idea what is happening with Linux/Py27?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea what is happening with Linux/Py27?

I could narrow it down to:

`conda create --name TEST python=2.7 py6s "rsgislib >=4.0.0"`

I'll try to check and re-build `py6s` and latest `rsgislib` to see if we can fix this.

**Comment by ocefpaf** [comment]
@gillins looks like there are more conflicts, if py27 is important to you we probably need to rebuild more stuff than just py6s.

**Comment by ocefpaf** [comment]
> @gillins looks like there are more conflicts, if py27 is important to you we probably need to rebuild more stuff than just py6s.

Looks like https://github.com/conda-forge/matplotlib-feedstock/pull/216 did the trick. Newer mpl are Python 3 only and `mpl 2.x` wasn't rebuilt in a while.

**Comment by petebunting** [comment]
> @gillins looks like there are more conflicts, if py27 is important to you we probably need to rebuild more stuff than just py6s.

Thanks for looks at this both. We don't need py27.

**Comment by gillins** [comment]
Thanks @ocefpaf ! Well done tracking that down.

**Pull request merged**
