### PR TITLE
Updated RSGISLib version to 3.4

### PR DESCRIPTION
**Pull request by danclewley**
Also removed GDAL as a dependency as will be pulled in from RSGISLib.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by gillins** [comment]
Linux py36 is getting `libgdal` from defaults, not sure how this is possible....

**Review by gillins — APPROVED** [review]

**Comment by gillins** [comment]
I'll try restarting...

**Comment by gillins** [comment]
@ocefpaf any ideas why this is failing for Linux and py36? Seems there is some subtle version problem causing `defaults` `gdal` to be picked up... Are you seeing this problem for other packages?

**Comment by danclewley** [comment]
I removed `gdal` as a dependency for `arcsi` as it will be pulled in with `rsgislib` - not sure if this is actually causing problems though.

**Comment by gillins** [comment]
Maybe add it back in and see if it helps? I notice that `arcsi` imports `gdal` directly so maybe technically should depend on `gdal` so it will be rebuilt if we bump the `gdal` version?

**Comment by gillins** [comment]
:+1:

**Pull request merged**
