### PR TITLE
python 3.8 not being built

### PR DESCRIPTION
**Pull request by petebunting**
…ilt.

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@ocefpaf @isuruf any idea why Python 3.8 isn't being built on this one?

**Comment by isuruf** [comment]
Because https://github.com/conda-forge/arcsi-feedstock/pull/10 wasn't merged.

**Comment by gillins** [comment]
Ah right - thanks! Will try and get that one going instead.

**Comment by gillins** [comment]
Fixed by #10. Thanks @isuruf !

**Pull request closed without merging**
